export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORIES_COLOR = "SET_CATEGORIES_COLOR";
export const GET_POSTS = "GET_POSTS";
export const SET_PAGINATION_CONFIG = "SET_PAGINATION_CONFIG";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";